[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  NODE_VERSION = "10.16.0" 
  YARN_VERSION = "1.22.0"

[context.deploy-preview]
  command = "yarn build-preview"

[[redirects]]
  from = "/our-team"
  to = "/index.html#leadership"
  status = 301
  force = false
