# NETLIFY CMS CONFIG

# Backend
#----------------------------------------------------#
backend:
  name: git-gateway
  repo: UncleSisu/redhook # Path to your Github repository
  branch: master # Branch to update (master by default)

# Editorial Workflow
#----------------------------------------------------#
# Enable to add an interface for drafting, reviewing, and approving
# publish_mode: editorial_workflow

# Media and Public Folders
#----------------------------------------------------#
# Folder where user uploaded files will be saved in the repo
media_folder: "src/images/uploads"

# Folder where upload files can be found on public site
# Used in image src attributes and is relative to the file where it’s called
# For this reason, we usually start the path at the site root, using the opening /.
# If public_folder is not set, Netlify CMS will default to the same value as media_folder, adding an opening / if one is not included.
public_folder: "/images/uploads"

# Collections
#----------------------------------------------------#
# Define the structure for the different content types the CMS should be able to edit
# name: Used in routes, e.g., /admin/collections/:slug/edit
# label: Used in the UI, e.g., "New Post"
# folder: The path to the folder where the documents are stored
# create: Allow users to create new documents in this collection
# fields: Fields shown in the content editor, then saved as front matter at the beginning of the document
#   label: Field label in the editor UI
#   name: Field name in the document front matter
#   widget: Determines UI style and value data type
#   default (optional) Sets a default value for the field
#   tagname: (optional) The HTML tag for the content preview window
collections:
  - name: "case-studies"
    label: "Case Study"
    folder: "src/markup/content/case-studies"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Call To Action", name: "call_to_action", widget: "string"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Grid Layout", name: "grid_layout", widget: "select", options: ["horizontal", "vertical"]}
      - label: "Services"
        name: "services"
        widget: "list"
        fields:
          - {label: "Service", name: "service", widget: "string"}
      - label: "Touts"
        name: "touts"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Details", name: "details", widget: "text"}
      - label: "Quote"
        name: "quote"
        widget: "object"
        fields:
          - {label: "Text", name: "text", widget: "markdown"}
          - {label: "Source's Name", name: "source_name", widget: "string"}
          - {label: "Source's Title", name: "source_title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Description (optional)", name: "description", widget: "string"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/markup/content/_index.md"
        label: "Home Page"
        name: "index"
        fields:
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Details", name: "details", widget: "text"}
